repos:
- repo: local
  hooks:
  # https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml
  - id: black
    name: black
    entry: black
    language: python
    language_version: python3.8
    require_serial: true
    types_or: [python, pyi]
