from pathlib import Path

from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from apispec_webframeworks.flask import FlaskPlugin

from timetable import app
from timetable.schemas.note import NoteFormSchema, NoteSchema
from timetable.views.note import save_note


@app.cli.command()
def gen():
    spec = APISpec(
        title='Timetable',
        version='0.1.0',
        openapi_version='3.0.2',
        info={'description': 'What have you done today?'},
        servers=[{'url': 'http://localhost:1234'}],
        plugins=[FlaskPlugin(), MarshmallowPlugin()]
    )

    spec.components.schema('NoteForm', schema=NoteFormSchema)
    spec.components.schema('Note', schema=NoteSchema)

    spec.path(view=save_note)

    spec_path = Path(__file__).parent.joinpath('../../openapi.yaml').resolve()
    with open(spec_path, 'w') as f:
        f.write('# DO NOT EDIT\n')
        f.write('# Auto generated by bin\\flask spec\n')
        f.write('\n')
        f.write(spec.to_yaml())

    app.logger.info(f'Generated {spec_path}')
