from pathlib import Path

from timetable import app
from timetable.openapi import spec


@app.cli.command()
def gen() -> None:
    spec_path = Path(__file__).parent.joinpath('../../openapi.yaml').resolve()
    with open(spec_path, 'w', encoding='utf-8') as f:
        f.write('# DO NOT EDIT\n')
        f.write('# Auto generated by "flask gen"\n')
        f.write('\n')
        f.write(spec.to_yaml())

    app.logger.info(f'Generated {spec_path}')
