/* tslint:disable */
/* eslint-disable */
/**
 * Timetable
 * What have you done today?
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteForm
 */
export interface NoteForm {
    /**
     * 
     * @type {string}
     * @memberof NoteForm
     */
    content?: string;
}

export function NoteFormFromJSON(json: any): NoteForm {
    return NoteFormFromJSONTyped(json, false);
}

export function NoteFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function NoteFormToJSON(value?: NoteForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

